### ISSUE TITLE
Bucket name to date returns incorrect month on every other month

### ISSUE THREAD

**Issue by lbkNhubert** [Thomas101/nest_history#1]
proposed change. Seems to work on my system

/**
- Converts a bucket name to a date
- @param name: the name
- @return a date object
  */
  var bucketNameToDate = function(name) {
  var components = name.split('_')
  var date = new Date(0)
  date.setYear(parseInt(components[0]))
  date.setMonth(parseInt(components[1]))
  date.setDate(parseInt(components[2]))
  //return date
  return new Date(parseInt(components[0]), parseInt(components[1]), parseInt(components[2]));
  }

**Comment by Thomas101** [comment]
Hi @lbkNhubert which browser are you using?

**Comment by lbkNhubert** [comment]
I am using vivaldi. I can revert my changes and test on other browsers if that will help.

**Comment by Thomas101** [comment]
It looks like a compatibility issue, but I've changed it to what you've suggested as that looks to be more robust. Thanks very much!
